In this notebook, I'm going to explore some of the fundamental concepts of tensors using tensor flow.

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.15.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix (A matrix has more than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) #specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# I learnt that a scalar is a tensor with '0' dimensions
# A vector is a tensor with '1' dimension, a matrix is a tensor with '2' dimensions
# And a tensor is a 'tensor' with 3 dimensions.

#### Creating tensors with 'tf.Variable'

In [ ]:
v= tf.Variable([10, 7])
scalar = tf.constant([10, 7])
v, scalar

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Changing one of the elements in the variable tensor
v[0].assign(7)
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

Random tensors are tensors of some arbitary size which contain random numbers

In [ ]:
# Create two random but the same tensors
random_1 = tf.random.uniform(shape=[2])
random_1
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.uniform(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
wen = tf.random.Generator.from_seed(16)
wen = tf.random.uniform(shape=(2, 2))
wen

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.9789473 , 0.7304721 ],
       [0.8219787 , 0.23440075]], dtype=float32)>

# Shuffling the order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3,4],
                            [5, 6]])
not_shuffled.ndim

2

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled, seed=12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# Generating Tensors with numpy arrays


In [ ]:
# Let's try this out
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int16, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int16)>,
 <tf.Tensor: shape=(24,), dtype=int16, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int16)>)

## Getting information from tensors
When dealing with tensors you want to be aware of the following attributes
- Shape
- Rank
- Axis or dimension
- Size

In [ ]:
# Create a rank 4 tensor (A tensor with 4 dimensions)
tensor_4 = tf.zeros(shape=(2, 3, 3, 4))
tensor_4

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_4.shape, tensor_4.ndim, tf.size(tensor_4)

(TensorShape([2, 3, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=72>)

In [ ]:
print("The dataType of our tensor is", tensor_4.dtype)
print(" The total number of elements in the tensor is:", tf.size(tensor_4))

The dataType of our tensor is <dtype: 'float32'>
 The total number of elements in the tensor is: tf.Tensor(72, shape=(), dtype=int32)


## Indexing tensors

Tensors can be indexed just like python lists

In [ ]:
# Getting the first 2 elements of each dimension
tensor_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except for the final one
tensor_4[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 3, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
tensor_2 = tf.ones(shape=[2,2])
tensor_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Getting the last item of the 2 dimensional tensor
tensor_2[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [ ]:
#Adding in extra dimension to our rank 2 tensor
tensor_3 = tensor_2[..., tf.newaxis]
tensor_3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [ ]:
# Expanding the dimension of a tensor
tf.expand_dims(tensor_2, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]]], dtype=float32)>

# Manipulating Tensors (Tensor Operations)
* *Basic operations **

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
ten = tf.constant([[10, 7], [3, 4]])
ten + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.multiply(ten, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.subtract(ten, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

**Matrix Multiplication**
In machine learning, matrix multiplication is one of the most comon tensor operations.

In [ ]:
# Matrix multiplication
print(ten)
tf.matmul(ten, ten)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
ten_1 = tf.constant([[1, 2, 5],
             [7, 2, 1],
            [3, 3, 3] ])
ten_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
ten_2 = tf.constant([[3,5],
                     [6, 7],
                     [1, 8]])
ten_2, ten_1, tf.matmul(ten_1, ten_2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>)

In [ ]:
ten @ ten, ten

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
#Can do reshape as same as transpose
tf.reshape(ten_2, shape=(2, 3)),
tf.transpose(ten_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

## Changing the datatypes of tensors


In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 4])
C.dtype

tf.int32

In [ ]:
#Changing from float32 to float16
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

## Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a samller amount of values.

In [ ]:
# Create a tensor and then get the absolute values
D = tf.constant([-7, 10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the sum of a tensor
* Get the mean of a tensor

In [ ]:
T = tf.constant([[2,3,4],[5,6,7]])
T

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

In [ ]:
#Getting the minimum
tf.reduce_min(T)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# Getting the maximum
tf.reduce_max(T)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Getting the mean
tf.reduce_mean(T)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
#Getting the sum
tf.reduce_sum(T).numpy()

27

In [ ]:
# Getting the variance
tf.math.reduce_std([[-1, 2.], [3., 4.]]).numpy()

1.8708286

**Find the positional maximum and minimum of a tensor**

In [ ]:
#Let's go: Creating a new tensor for finding positional maximum or minimum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
## Indexing the largest positional value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Confirming with tf.max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

# Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.random.uniform([1,1,1,30])
G, G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 30), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 30]),
 4)

In [ ]:
# Squeezing
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.ndim

(<tf.Tensor: shape=(30,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
       dtype=float32)>,
 1)

# One-hot encoding tensors

In [ ]:
some_list = [0, 1, 2, 3] # could be red, green, blue,
tf.one_hot(some_list, depth=4) # This encodes the values in the array of somelist into numerical values for tensors to be able to understand.


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## More mathematical operations: Squaring, log, square root

In [ ]:
# Let's go: Create a new tensor
H =tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# To square the tensor:
tf.square(H) # This squares the values in the tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Getting the square root:
tf.sqrt(tf.cast(H, dtype=tf.float16)) # We had to cast because dtype=int32 is not an allowed dtype in the square root function of tensor flow
# The only allowed datatypes are: float32, float16, complex32, complex64..except int{}

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the log of a tensor:
tf.math.log(tf.cast(H, dtype=tf.float16)) #The log function in TF doesn't allow the int dtype as well
# And it also doesn't omit the '.math' naming.

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and Numpy

In [ ]:
# Create a tensor directly from a Numpy array:
J = tf.constant(np.arange(3))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 2])>

In [ ]:
# Convert our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([0, 1, 2]), numpy.ndarray)

## Finding Access to GPUs

In [ ]:
tf.config.list_physical_devices() #To get the available device on which our tensor is running


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
## To connect to a GPU, you go to a RunTime, select change runtime type, and then choose GPU.
